config/routes.rb
Rails.application.routes.draw do
  resources :tyres
  resources :vehicles do
  collection do
    get 'speed'
  end
end
resources :positions do
  collection do
    get 'marker'
    get 'routes'
  end
end
  root to: "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id         :integer          not null, primary key
#  latitude   :float
#  longitude  :float
#  speed      :integer
#  imei       :text
#  period     :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Position < ApplicationRecord
end

app/models/tyre.rb
# == Schema Information
#
# Table name: tyres
#
#  id             :integer          not null, primary key
#  brand          :string
#  serial         :text
#  start_distance :decimal(, )
#  total_distance :decimal(, )
#  status         :string
#  vehicle_id     :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Tyre < ApplicationRecord
  belongs_to :vehicle
end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id         :integer          not null, primary key
#  plate      :text
#  imei       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  distance   :decimal(, )
#

class Vehicle < ApplicationRecord
  has_many :tyres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
    @vehicles = Vehicle.all
  end

  def marker
    len = Vehicle.all.size
    allVehiclePos = Array.new
    for i in 1..len
      id = Vehicle.all.find(i).id
      plate = Vehicle.all.find(i).plate
      imei = Vehicle.all.find(i).imei
      position = Position.all.where(imei: imei).last
      ary = Array.new
      ary.push(id, plate, position.latitude, position.longitude)
      allVehiclePos.push(ary)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: allVehiclePos }
    end
  end
  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:latitude, :longitude, :speed, :imei, :period)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @positions = Position.all
    @vehicles = Vehicle.all
  end

  def about
  end
end

app/controllers/tyres_controller.rb
class TyresController < ApplicationController
  before_action :set_tyre, only: [:show, :edit, :update, :destroy]

  # GET /tyres
  # GET /tyres.json
  def index
    @tyres = Tyre.all
  end

  # GET /tyres/1
  # GET /tyres/1.json
  def show
  end

  # GET /tyres/new
  def new
    @tyre = Tyre.new
  end

  # GET /tyres/1/edit
  def edit
  end

  # POST /tyres
  # POST /tyres.json
  def create
    @tyre = Tyre.new(tyre_params)

    respond_to do |format|
      if @tyre.save
        format.html { redirect_to @tyre, notice: 'Tyre was successfully created.' }
        format.json { render :show, status: :created, location: @tyre }
      else
        format.html { render :new }
        format.json { render json: @tyre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tyres/1
  # PATCH/PUT /tyres/1.json
  def update
    respond_to do |format|
      if @tyre.update(tyre_params)
        format.html { redirect_to @tyre, notice: 'Tyre was successfully updated.' }
        format.json { render :show, status: :ok, location: @tyre }
      else
        format.html { render :edit }
        format.json { render json: @tyre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tyres/1
  # DELETE /tyres/1.json
  def destroy
    @tyre.destroy
    respond_to do |format|
      format.html { redirect_to tyres_url, notice: 'Tyre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tyre
      @tyre = Tyre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tyre_params
      params.require(:tyre).permit(:brand, :serial, :start_distance, :total_distance, :status, :truck_id)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:plate, :imei)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tyres_helper.rb
module TyresHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Dashboard</a>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" onclick="reload()" href="<%= root_path %>">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= tyres_path%>">Tyres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
<script>
  function reload(){
    location.reload();
  }
</script>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
   <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
     <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
   <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
    <title>Dashboard for Logistics App</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap-material-design.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>
    <%= csrf_meta_tags %>
    <%= yield :js_html %>
  <script>
    <%= yield :js %>
  </script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :position_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :position_longitude %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed, id: :position_speed %>
  </div>

  <div class="field">
    <%= form.label :imei %>
    <%= form.text_area :imei, id: :position_imei %>
  </div>

  <div class="field">
    <%= form.label :period %>
    <%= form.date_select :period, id: :position_period %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<!-- <script type="text/javascript">
    $('select').select2();
</script> -->

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>Coffeelike by TEMPLATED</title>
        <link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
		<div id="bg">
			<div id="outer">
				<div id="header">
					<div id="logo">
						<h1>
							<a href="#">Coffeelike</a>
						</h1>
					</div>
					<div id="nav">
						<ul>
							<li class="first active">
								<a href="#">Home</a>
							</li>
							<li>
								<a href="#">Services</a>
							</li>
							<li>
								<a href="#">Portfolio</a>
							</li>
							<li>
								<a href="#">About</a>
							</li>
							<li>
								<a href="#">Blog</a>
							</li>
							<li class="last">
								<a href="#">Contact</a>
							</li>
						</ul>
						<br class="clear" />
					</div>
				</div>
				<div id="main">
					<div id="sidebar" align="center">
            <div align="center"><font>ค้นหาทะเบียนรถ</font></div>
            <div align="center">
              <select id="plate"style="width:115px;" class="js-example-basic-single" name="state">
                <% @vehicles.each do |vehicle| %>
                  <option value="<%= vehicle.id %>"> <%= vehicle.plate %> </option>
                <% end %>
              </select>
              &nbsp
              <button onclick="vehicleSearch()" class="search-button">ค้นหา</button>
            </div>
						<ul class="linkedList">
							<li class="first">
                <br>
                <div id="smallbox" style="height:300px;width:200px;border:1.5px solid #ccc;font:13px/23px Georgia, Garamond, Serif;overflow:auto;">
                  <table>
                    <thead>
                      <tr bgcolor="#FF0000">
                        <th><font color="black">Plate</font></th>
                        <th><font color="black">Imei</font></th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @vehicles.each do |vehicle| %>
                        <tr>
                          <td><font color="black"><%= vehicle.plate %></font></td>
                          <td><font color="black"><%= vehicle.imei %></font></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
							</li>
						</ul>
					</div>
					<div id="content">
						<div id="box1">
              <div id="dvMap" style="width: 754px; height: 530px">
              </div>
							<img class="left" width="130" height="160" alt="" />
							<p>
								This is <strong>Coffeelike</strong>, a two column CSS template by
								<a href="http://templated.co" rel="nofollow">TEMPLATED</a> with photos from
								<a href="http://www.pdphoto.org/">PDPhoto</a>. It's released (for free) under the
								<a href="http://templated.co/license/">Creative Commons Attribution license</a>,
								so feel free to use it for any personal or commercial work (just give us credit for it).
								Hit up our <a href="http://templated.co">website</a> for more awesomely
								cool free templates, and follow us on <a href="http://twitter.com/templatedco">Twitter</a>
								(<a href="http://twitter.com/templatedco">@templatedco</a>) for updates, announcements, and other
								mildly interesting ramblings.
							</p>
						</div>
						<div id="box2">
							<h3>
								Primis dolor fringilla porta
							</h3>
							<ul class="imageList">
								<li class="first">
									<img class="left" width="80" height="80" alt="" /> <span>Quis faucibus mauris quis consectetur lobortis parturient sit turpis scelerisque neque aliquet.</span>
								</li>
								<li>
									<img class="left" width="80" height="80" alt="" /> <span>Lobortis malesuada penatibus porta varius ligula blandit sit dolor mattis morbi ullamcorper posuere tempus.</span>
								</li>
								<li class="last">
									<img class="left" width="80" height="80" alt="" /> <span>Diam nunc turpis placerat imperdiet ac cras ac sociis aliquam sed lacinia augue suspendisse.</span>
								</li>
							</ul>
						</div>
						<div id="box3">
							<h3>
								Magnis felis
							</h3>
							<p>
								Vulputate magna nibh augue. Rutrum nibh sodales porta etiam.
							</p>
							<ul class="linkedList">
								<li class="first">
									<a href="#">Lobortis fringilla dictum cras</a>
								</li>
								<li>
									<a href="#">Erat primis accumsan facilisis</a>
								</li>
								<li>
									<a href="#">Laoreet in in magna</a>
								</li>
								<li>
									<a href="#">Porta a vulputate placerat</a>
								</li>
								<li class="last">
									<a href="#">Neque rhoncus rhoncus iaculis</a>
								</li>
							</ul>
						</div>
						<br class="clear" />
					</div>
					<br class="clear" />
				</div>
			</div>
			<div id="copyright">
				&copy; Your Site Name | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>
			</div>
		</div>
    </body>
</html>

<script>
  function vehicleSearch() {
    vehecle_id = document.getElementById("plate").value
    for (i = 0; i < markersArray.length; i++) {
      if (markersArray[i].name[0] == vehecle_id) {
          map.setZoom(13);
          map.setCenter(markersArray[i].getPosition());
          // console.log(markersArray[i])
      } else
         console.log("")
    }


    // console.log(markersArray[0].name[0])
    // vehecle_id = document.getElementById("plate").value
  }
</script>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @position.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @position.longitude %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @position.speed %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @position.imei %>
</p>

<p>
  <strong>Period:</strong>
  <%= @position.period %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>

app/views/tyres/_form.html.erb
<%= form_with(model: tyre, local: true) do |form| %>
  <% if tyre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tyre.errors.count, "error") %> prohibited this tyre from being saved:</h2>

      <ul>
      <% tyre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :tyre_brand %>
  </div>

  <div class="field">
    <%= form.label :serial %>
    <%= form.text_area :serial, id: :tyre_serial %>
  </div>

  <div class="field">
    <%= form.label :start_distance %>
    <%= form.text_field :start_distance, id: :tyre_start_distance %>
  </div>

  <div class="field">
    <%= form.label :total_distance %>
    <%= form.text_field :total_distance, id: :tyre_total_distance %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :tyre_status %>
  </div>

  <div class="field">
    <%= form.label :truck_id %>
    <%= form.text_field :truck_id, id: :tyre_truck_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tyres/edit.html.erb
<h1>Editing Tyre</h1>

<%= render 'form', tyre: @tyre %>

<%= link_to 'Show', @tyre %> |
<%= link_to 'Back', tyres_path %>

app/views/tyres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tyres</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Serial</th>
      <th>Start distance</th>
      <th>Total distance</th>
      <th>Status</th>
      <th>Truck</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tyres.each do |tyre| %>
      <tr>
        <td><%= tyre.brand %></td>
        <td><%= tyre.serial %></td>
        <td><%= tyre.start_distance %></td>
        <td><%= tyre.total_distance %></td>
        <td><%= tyre.status %></td>
        <td><%= tyre.truck %></td>
        <td><%= link_to 'Show', tyre %></td>
        <td><%= link_to 'Edit', edit_tyre_path(tyre) %></td>
        <td><%= link_to 'Destroy', tyre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tyre', new_tyre_path %>

app/views/tyres/new.html.erb
<h1>New Tyre</h1>

<%= render 'form', tyre: @tyre %>

<%= link_to 'Back', tyres_path %>

app/views/tyres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @tyre.brand %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @tyre.serial %>
</p>

<p>
  <strong>Start distance:</strong>
  <%= @tyre.start_distance %>
</p>

<p>
  <strong>Total distance:</strong>
  <%= @tyre.total_distance %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tyre.status %>
</p>

<p>
  <strong>Truck:</strong>
  <%= @tyre.truck %>
</p>

<%= link_to 'Edit', edit_tyre_path(@tyre) %> |
<%= link_to 'Back', tyres_path %>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plate %>
    <%= form.text_area :plate, id: :vehicle_plate %>
  </div>

  <div class="field">
    <%= form.label :imei %>
    <%= form.text_area :imei, id: :vehicle_imei %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Plate</th>
      <th>Imei</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.plate %></td>
        <td><%= vehicle.imei %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plate:</strong>
  <%= @vehicle.plate %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @vehicle.imei %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>